###
GET http://localhost:8080/api/v1/schedules?page=1
Content-Type: application/json
Accept: application/json
###

###
POST http://localhost:8080/api/v1/schedules
Content-Type: application/json
Accept: application/json

{
    "employee_id": 9,
    "status_id": 10,
    "date": "2025-08-15",
    "description": "Ответственный руководитель"
}
###

###
GET http://localhost:8080/api/v1/schedules/34657
Content-Type: application/json
Accept: application/json
###

###
PUT http://localhost:8080/api/v1/schedules/34657
Content-Type: application/json
Accept: application/json

{
    "employee_id": 9,
    "status_id": 9,
    "date": "2025-08-15",
    "description": "Ответственный руководитель"
}
###

###
DELETE http://localhost:8080/api/v1/schedules/34657
Content-Type: application/json
Accept: application/json
###
